// AUTO-GENERATED by scripts/sync-kit.mjs from kit/. Do not edit here; edit kit/ and re-run. (source: kit/assets.d.ts)
// Ambient declaration so panels can `import '../_kit/cate-kit.css'` as a
// side-effect (the bundler injects the stylesheet; tsc just needs it to type).
declare module '*.css'
