#!/usr/bin/env node
// =============================================================================
// sync-kit.mjs — propagate the shared UI kit into each consuming extension.
//
// `kit/` is the single source of truth (cate-kit.css, theme.ts,
// service-connection.ts, cate-host.d.ts). Extensions can't share a node package
// in this no-monorepo layout and each must build self-contained, so we copy the
// kit into `extensions/<id>/src/_kit/`. The copies are committed (so tests and
// the IDE work with no pre-step); run this whenever kit/ changes. build.sh runs
// it before building.
//
//   node scripts/sync-kit.mjs          copy kit/ -> each consumer's src/_kit/
//   node scripts/sync-kit.mjs --check  fail if any copy is stale (for CI)
// =============================================================================
import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } from 'node:fs'
import { join, dirname, extname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const KIT_DIR = join(ROOT, 'kit')
const EXT_DIR = join(ROOT, 'extensions')

// Extensions that build their UI on the kit. excalidraw is a full-bleed
// upstream component with no Cate chrome to theme; frontendkit/kitchensink are
// dev references. All three are deliberately excluded.
const KIT_CONSUMERS = [
  'cate.taskmaster',
  'cate.mcphub',
  'cate.sourcebot',
  'cate.deepwiki',
  'cate.datasette',
  'cate.hoppscotch',
]

const BANNER_PREFIX = 'AUTO-GENERATED by scripts/sync-kit.mjs from kit/. Do not edit here; edit kit/ and re-run.'

function banner(file) {
  const line = `${BANNER_PREFIX} (source: kit/${file})`
  return extname(file) === '.css' ? `/* ${line} */\n` : `// ${line}\n`
}

// Only source files ship into _kit/ (skip README.md, tsconfig.check.json, etc).
const kitFiles = readdirSync(KIT_DIR).filter((f) => /\.(ts|css)$/.test(f))
const check = process.argv.includes('--check')
let stale = 0
let wrote = 0

for (const id of KIT_CONSUMERS) {
  const dest = join(EXT_DIR, id, 'src', '_kit')
  if (!existsSync(join(EXT_DIR, id))) {
    console.warn(`sync-kit: skip ${id} (not found)`)
    continue
  }
  if (!check) mkdirSync(dest, { recursive: true })
  for (const file of kitFiles) {
    const content = banner(file) + readFileSync(join(KIT_DIR, file), 'utf8')
    const target = join(dest, file)
    const current = existsSync(target) ? readFileSync(target, 'utf8') : null
    if (current === content) continue
    if (check) {
      console.error(`sync-kit: STALE ${id}/src/_kit/${file}`)
      stale++
      continue
    }
    writeFileSync(target, content)
    console.log(`sync-kit: ${id}/src/_kit/${file}`)
    wrote++
  }
}

if (check) {
  if (stale) {
    console.error(`sync-kit: ${stale} file(s) out of date — run \`node scripts/sync-kit.mjs\``)
    process.exit(1)
  }
  console.log('sync-kit: all consumers up to date')
} else {
  console.log(`sync-kit: done (${wrote} file(s) updated)`)
}
