#!/usr/bin/env node
// =============================================================================
// sync-kit.mjs — propagate the shared UI kit into each consuming extension.
//
// `kit/` is the single source of truth (cate-kit.css, theme.ts,
// service-connection.ts, cate-host.d.ts). Extensions can't share a node package
// in this no-monorepo layout and each must build self-contained, so we copy the
// kit into `extensions/<id>/src/_kit/`. The copies are committed (so tests and
// the IDE work with no pre-step); run this whenever kit/ changes. build.sh runs
// it before building.
//
//   node scripts/sync-kit.mjs          copy kit/ -> each consumer's src/_kit/
//   node scripts/sync-kit.mjs --check  fail if any copy is stale (for CI)
// =============================================================================
import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } from 'node:fs'
import { join, dirname, extname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const KIT_DIR = join(ROOT, 'kit')
const EXT_DIR = join(ROOT, 'extensions')

// Extensions that build their UI on the kit (browser files → src/_kit/).
// excalidraw is a full-bleed upstream component with no Cate chrome to theme;
// frontendkit/kitchensink are dependency-free dev references. Those are
// deliberately excluded — they keep standalone copies on purpose.
const KIT_CONSUMERS = [
  'cate.sqlite',
  'cate.mcp',
  'cate.aisession',
]

// Extensions with a Node server that share the kit's HTTP scaffolding. These
// files import `http`/`fs`, so they land in src/_kitserver/ (which the Node
// tsconfigs include and the browser tsconfigs do not) rather than src/_kit/.
const SERVER_CONSUMERS = [
  'cate.sqlite',
  'cate.mcp',
]

const BANNER_PREFIX = 'AUTO-GENERATED by scripts/sync-kit.mjs from kit/. Do not edit here; edit kit/ and re-run.'

function banner(file) {
  const line = `${BANNER_PREFIX} (source: kit/${file})`
  return extname(file) === '.css' ? `/* ${line} */\n` : `// ${line}\n`
}

// Top-level source files ship into _kit/ (skip README.md, tsconfig.check.json,
// and the server/ subdir, which is its own tier).
const kitFiles = readdirSync(KIT_DIR).filter((f) => /\.(ts|css)$/.test(f))
const SERVER_KIT_DIR = join(KIT_DIR, 'server')
const serverKitFiles = existsSync(SERVER_KIT_DIR)
  ? readdirSync(SERVER_KIT_DIR).filter((f) => /\.ts$/.test(f))
  : []
const check = process.argv.includes('--check')
let stale = 0
let wrote = 0

// Copy `files` from `srcDir` into each consumer's `subdir`, keeping committed
// copies byte-identical (banner + source). In --check mode, report staleness
// instead of writing.
function syncTier(consumers, srcDir, srcLabelPrefix, subdir) {
  for (const id of consumers) {
    const dest = join(EXT_DIR, id, 'src', subdir)
    if (!existsSync(join(EXT_DIR, id))) {
      console.warn(`sync-kit: skip ${id} (not found)`)
      continue
    }
    if (!check) mkdirSync(dest, { recursive: true })
    for (const file of files(srcDir)) {
      const content = banner(join(srcLabelPrefix, file)) + readFileSync(join(srcDir, file), 'utf8')
      const target = join(dest, file)
      const current = existsSync(target) ? readFileSync(target, 'utf8') : null
      if (current === content) continue
      if (check) {
        console.error(`sync-kit: STALE ${id}/src/${subdir}/${file}`)
        stale++
        continue
      }
      writeFileSync(target, content)
      console.log(`sync-kit: ${id}/src/${subdir}/${file}`)
      wrote++
    }
  }
}

// Bind the file list per tier (kept out of syncTier so the banner label stays
// relative to kit/).
const TIER_FILES = new Map([
  [KIT_DIR, kitFiles],
  [SERVER_KIT_DIR, serverKitFiles],
])
function files(srcDir) {
  return TIER_FILES.get(srcDir) ?? []
}

syncTier(KIT_CONSUMERS, KIT_DIR, '', '_kit')
syncTier(SERVER_CONSUMERS, SERVER_KIT_DIR, 'server', '_kitserver')

if (check) {
  if (stale) {
    console.error(`sync-kit: ${stale} file(s) out of date — run \`node scripts/sync-kit.mjs\``)
    process.exit(1)
  }
  console.log('sync-kit: all consumers up to date')
} else {
  console.log(`sync-kit: done (${wrote} file(s) updated)`)
}
